### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by TY10909** [iqdxa/iqdxa.github.io#1]
哥们，推荐你用butterfly主题，嗯，我感觉比next主题好看些。当然next比较轻便，简洁。只是提个意见

**Comment by TY10909** [comment]
butterfly主题作者博客   butterfly.js.org
我的 js.wsp2003.xyz
还有一些其它的都很好看，各种魔改
比如  anzhiy.cn    和     blog.zhheo.com

**Comment by TY10909** [comment]
如果你是大佬别喷我啊，怕被骂
![02E0787F](https://user-images.githubusercontent.com/112875745/216824056-7f9582a2-9f32-4858-8fbb-e2046935d8dc.png)

**Comment by iqdxa** [comment]
好的我去看看。我只是才了解这个，也不咋会

**Comment by TY10909** [comment]
你可以直接在butterfly.js.org官方文档内看如何使用，其实

**Comment by TY10909** [comment]
实际上还有一些人将他们魔改后的也开源了

**Comment by iqdxa** [comment]
OK，我已经改成butterfly主题了。先大概设置了一下，以后再慢慢弄。这个主题确实好看，谢谢推荐。
